// <auto-generated />
using System;
using CompleteDeveloperNetwork_System.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CompleteDeveloperNetwork_System.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20250926023815_IntialCreate")]
    partial class IntialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CompleteDeveloperNetwork_System.Models.Developers", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("IsActive")
                        .HasColumnType("int");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Udatetime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("developers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "alice@example.com",
                            IsActive = 1,
                            PhoneNumber = "0123456789",
                            Udatetime = new DateTime(2025, 9, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Username = "alice_dev"
                        },
                        new
                        {
                            Id = 2,
                            Email = "bob@example.com",
                            IsActive = 1,
                            PhoneNumber = "0198765432",
                            Udatetime = new DateTime(2025, 9, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Username = "bob_coder"
                        },
                        new
                        {
                            Id = 3,
                            Email = "charlie@example.com",
                            IsActive = 1,
                            PhoneNumber = "0182222333",
                            Udatetime = new DateTime(2025, 9, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Username = "charlie_pro"
                        });
                });

            modelBuilder.Entity("CompleteDeveloperNetwork_System.Models.Hobbies", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DeveloperId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DeveloperId");

                    b.ToTable("Hobbies");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Weekend rides",
                            DeveloperId = 1,
                            Name = "Cycling"
                        },
                        new
                        {
                            Id = 2,
                            Description = "FPS games",
                            DeveloperId = 1,
                            Name = "Gaming"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Landscape photography",
                            DeveloperId = 2,
                            Name = "Photography"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Trying new recipes",
                            DeveloperId = 2,
                            Name = "Cooking"
                        },
                        new
                        {
                            Id = 5,
                            Description = "Exploring new places",
                            DeveloperId = 3,
                            Name = "Traveling"
                        });
                });

            modelBuilder.Entity("CompleteDeveloperNetwork_System.Models.Skillsets", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DeveloperId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DeveloperId");

                    b.ToTable("Skillsets");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Backend development",
                            DeveloperId = 1,
                            Name = "C#"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Frontend development",
                            DeveloperId = 1,
                            Name = "React"
                        },
                        new
                        {
                            Id = 3,
                            Description = "AI/ML coding",
                            DeveloperId = 2,
                            Name = "Python"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Database management",
                            DeveloperId = 2,
                            Name = "SQL"
                        },
                        new
                        {
                            Id = 5,
                            Description = "Enterprise systems",
                            DeveloperId = 3,
                            Name = "Java"
                        });
                });

            modelBuilder.Entity("CompleteDeveloperNetwork_System.Models.Hobbies", b =>
                {
                    b.HasOne("CompleteDeveloperNetwork_System.Models.Developers", "developers")
                        .WithMany("hobbies")
                        .HasForeignKey("DeveloperId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("developers");
                });

            modelBuilder.Entity("CompleteDeveloperNetwork_System.Models.Skillsets", b =>
                {
                    b.HasOne("CompleteDeveloperNetwork_System.Models.Developers", "developers")
                        .WithMany("skillsets")
                        .HasForeignKey("DeveloperId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("developers");
                });

            modelBuilder.Entity("CompleteDeveloperNetwork_System.Models.Developers", b =>
                {
                    b.Navigation("hobbies");

                    b.Navigation("skillsets");
                });
#pragma warning restore 612, 618
        }
    }
}
